name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        yarn add surge

    - name: Build site
      run: |
        yarn run build
        yarn run export
      env:
        NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID }}
        NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}

#     - name: Deploy
#       run: npx surge ./out calpoly.hack4impact.org
#       env:
#         SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
#         SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
