name: Lint

on: [pull_request]

jobs:
  run-linter:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18.16.1

    - run: yarn install
    - run: yarn run lint
